### ISSUE TITLE
Impossibile accedere a "I tuoi client e-service" in Collaudo

### ISSUE THREAD

**Issue by AlessioMarinelli** [pagopa/pdnd-interop-frontend#670]
**Descrivi il bug**
Nell'ambiente di Collaudo, cliccando su "I tuoi client e-service", si riceve un messaggio di "Errore del server" e non è possibile visualizzare la pagina

**Step per riprodurre il bug**
1. Vai su 'Interoperabilità Collaudo'
2. Clicca su 'I tuoi client e-service'
3. Vedi l'errore "Errore del server - Si è verificato un errore nella gestione della richiesta. Per favore, riprova."
4. Anche cliccando su "Riprova" il risultato è lo stesso

**Comportamento atteso**
Il comportamento atteso è visualizzare con successo l'elenco dei client e-service creati, per poterli modificare e/o crearne di nuovi

**Il codice IPA del tuo ente**
r_marche

**Data e ora in cui si è riscontrato il problema**
14/12/2023 09:20

**Ambiente**
Collaudo (l'errore non si presenta in Produzione)

**Quali permessi ha la tua utenza?**
Amministratore 

**Screenshot**
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/6f15ffc5-e5c1-4f71-8750-26a2735cc9b3)

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/919c7dee-8bc9-4032-86b7-c2f3a7c52ed7)

**Note**
Stacktrace in DevTools:

`GET https://selfcare.uat.interop.pagopa.it/backend-for-frontend/1.0/clients?kind=CONSUMER&limit=10&offset=0 500 (Internal Server Error) `

```
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at LNe (https://selfcare.uat.interop.pagopa.it/ui/assets/index-3bdbe330.js:390:1060)\n    at XMLHttpRequest.p (https://selfcare.uat.interop.pagopa.it/ui/assets/index-3bdbe330.js:390:4375)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer [REDACTED]",
            "Accept-Language": "it-IT",
            "X-Correlation-Id": "50029973-c62a-479a-8f2e-78e921097f28"
        },
        "paramsSerializer": {},
        "params": {
            "kind": "CONSUMER",
            "limit": 10,
            "offset": 0
        },
        "method": "get",
        "url": "https://selfcare.uat.interop.pagopa.it/backend-for-frontend/1.0/clients"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}
```

**Comment by AlessioMarinelli** [comment]
Questa mattina l'interfaccia sembra funziona correttamente
