### ISSUE TITLE
Aiuto servizio pdnd

### ISSUE THREAD

**Issue by Gavriel17** [pagopa/pdnd-interop-frontend#770]
Ciao ragazzi,

ho un problema nello staccare il Token autorizzativo del servizio tramite codice Java.

 

Di seguito il mio codice:

 

                                               HashMap<String, String> params = new HashMap<>();

                                               params.put("client_id", #IL MIO CLINET ID#);

                                               params.put("client_assertion", #LA MIA CLIENT ASSERTION#);

                                               params.put("client_assertion_type", "urn:ietf:params:oauth:client-assertion-type:jwt-bearer");

                                               params.put("grant_type", "client_credentials");

                                               byte[] postData = getDataString(params).getBytes( StandardCharsets.UTF_8 );

                                               int postDataLength = postData.length;

                                               String request = https://auth.interop.pagopa.it/token.oauth2;

                                               URL url = new URL( request );

                                               HttpsURLConnection conn= (HttpsURLConnection) url.openConnection();   

                                               conn.setDoOutput(true);

                                               conn.setInstanceFollowRedirects(false);

                                               conn.setRequestMethod("POST");

                                               conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

                                               conn.setRequestProperty("charset", "utf-8");

                                               conn.setRequestProperty("Content-Length", Integer.toString(postDataLength));

                                               conn.setUseCaches(false);

                                               try(DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {

                                                  wr.write( postData );

                                               }

                                              

                                               private static String getDataString(HashMap<String, String> params) throws UnsupportedEncodingException{

                                               StringBuilder result = new StringBuilder();

                                               boolean first = true;

                                               for(Map.Entry<String, String> entry : params.entrySet()){

                        if (first)

                            first = false;

                        else

                            result.append("&");   

                        result.append(URLEncoder.encode(entry.getKey(), "UTF-8"));

                        result.append("=");

                        result.append(URLEncoder.encode(entry.getValue(), "UTF-8"));

                                               }   

                                               return result.toString();

                }

 

 

L'errore che prendo è il seguente:

 

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.ssl.Alert.createSSLException(Alert.java:131)

                at sun.security.ssl.TransportContext.fatal(TransportContext.java:370)

                at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)

                at sun.security.ssl.TransportContext.fatal(TransportContext.java:308)

                at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:652)

                at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)

                at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)

                at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)

                at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:479)

                at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:457)

                at sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)

                at sun.security.ssl.SSLTransport.decode(SSLTransport.java:155)

                at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1320)

                at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1233)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:417)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:389)

                at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:558)

                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)

                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)

                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)

                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)

                at it.metlife.pdnd.api.PdndHttpClient.aliveClientTest(PdndHttpClient.java:126)

                at it.metlife.pdnd.api.PdndHttpClient.main(PdndHttpClient.java:55)

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)

                at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)

                at sun.security.validator.Validator.validate(Validator.java:271)

                at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)

                at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)

                at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:128)

                at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:636)

                ... 18 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

                at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

                at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

                at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)

                ... 24 more

               

Non capisco come risolverlo. Non dovrebbe esserci un problema di certificato sul servizio https://auth.interop.pagopa.it/token.oauth2.

Stessa chiamata con stessi parametri da Postman funziona.

 

Grazie per chi mi aiuterà.

**Comment by FedericaSicchiero** [comment]
Ciao, ci guardiamo e ti facciamo sapere!

**Comment by FedericaSicchiero** [comment]
Ciao, abbiamo controllato lato nostro e il problema sembra essere nel certificato lato vostro, perchè quello esposto da noi è valido.
Consigliamo di fare un controllo a livello locale per escludere eventuali override.

**Comment by Gavriel17** [comment]
Ciao,
Ma che vuol dire certificato lato nostro?
Per staccare quel token non serve un certificato

**Comment by Gavriel17** [comment]
Ci sono novità?
Se ci sono dei certificati da importare per chiamare questi servizi, potete passarmeli?
Grazie!

**Comment by beetlecrunch** [comment]
Buongiorno le url esposte da Interoperabilità sono associate a certificati validi rilasciati da CA.
L'errore segnalatoci è generato lato client e non server, pertanto non possiamo in alcun modo intervenire.
Quello che possiamo consigliarvi è di verificare le impostazioni sulle vostre macchine in particolare se il thrust store è aggiornato o magari è stato fatto un override di quello di default.
Ad ogni modo è sempre possibile aggiungere un certificato al proprio set di chiavi locali.
Per recuperare il nostro è sufficiente esportarlo direttamente da [qui](https://auth.interop.pagopa.it/token.oauth2).
